version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - "/var/lib/door/ollama:/root/.ollama"
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      OLLAMA_CONTEXT_LENGTH: 32786
      OLLAMA_KV_CACHE_TYPE: "${CONTEXT_QUANT_TYPE:-f16}"


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "${OPENWEBUI_PORT:-3030}:8080"
    volumes:
      - "/var/lib/door/open-webui:/app/backend/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama:
  open-webui: